package org.fdroid.index.v1;

import ch.qos.logback.core.joran.action.Action;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.bouncycastle.asn1.cmp.PKIFailureInfo;
import org.bouncycastle.i18n.ErrorBundle;
import org.fdroid.fdroid.views.apps.AppListActivity;
/* compiled from: AppV1.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"org/fdroid/index/v1/AppV1.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lorg/fdroid/index/v1/AppV1;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", Action.VALUE_ATTRIBUTE, "index_release"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes2.dex */
public final class AppV1$$serializer implements GeneratedSerializer {
    public static final AppV1$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    private AppV1$$serializer() {
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        AppV1$$serializer appV1$$serializer = new AppV1$$serializer();
        INSTANCE = appV1$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("org.fdroid.index.v1.AppV1", appV1$$serializer, 31);
        pluginGeneratedSerialDescriptor.addElement("categories", true);
        pluginGeneratedSerialDescriptor.addElement("antiFeatures", true);
        pluginGeneratedSerialDescriptor.addElement(ErrorBundle.SUMMARY_ENTRY, true);
        pluginGeneratedSerialDescriptor.addElement("description", true);
        pluginGeneratedSerialDescriptor.addElement("changelog", true);
        pluginGeneratedSerialDescriptor.addElement("translation", true);
        pluginGeneratedSerialDescriptor.addElement("issueTracker", true);
        pluginGeneratedSerialDescriptor.addElement("sourceCode", true);
        pluginGeneratedSerialDescriptor.addElement("binaries", true);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement("authorName", true);
        pluginGeneratedSerialDescriptor.addElement("authorEmail", true);
        pluginGeneratedSerialDescriptor.addElement("authorWebSite", true);
        pluginGeneratedSerialDescriptor.addElement("authorPhone", true);
        pluginGeneratedSerialDescriptor.addElement("donate", true);
        pluginGeneratedSerialDescriptor.addElement("liberapayID", true);
        pluginGeneratedSerialDescriptor.addElement("liberapay", true);
        pluginGeneratedSerialDescriptor.addElement("openCollective", true);
        pluginGeneratedSerialDescriptor.addElement("bitcoin", true);
        pluginGeneratedSerialDescriptor.addElement("litecoin", true);
        pluginGeneratedSerialDescriptor.addElement("flattrID", true);
        pluginGeneratedSerialDescriptor.addElement("suggestedVersionName", true);
        pluginGeneratedSerialDescriptor.addElement("suggestedVersionCode", true);
        pluginGeneratedSerialDescriptor.addElement("license", false);
        pluginGeneratedSerialDescriptor.addElement("webSite", true);
        pluginGeneratedSerialDescriptor.addElement("added", true);
        pluginGeneratedSerialDescriptor.addElement("icon", true);
        pluginGeneratedSerialDescriptor.addElement("packageName", false);
        pluginGeneratedSerialDescriptor.addElement(AppListActivity.SortClause.LAST_UPDATED, true);
        pluginGeneratedSerialDescriptor.addElement("localized", true);
        pluginGeneratedSerialDescriptor.addElement("allowedAPKSigningKeys", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] childSerializers() {
        KSerializer[] kSerializerArr;
        kSerializerArr = AppV1.$childSerializers;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        return new KSerializer[]{kSerializerArr[0], kSerializerArr[1], BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(stringSerializer), stringSerializer, BuiltinSerializersKt.getNullable(longSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[29]), BuiltinSerializersKt.getNullable(kSerializerArr[30])};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    public AppV1 deserialize(Decoder decoder) {
        KSerializer[] kSerializerArr;
        List list;
        List list2;
        String str;
        String str2;
        String str3;
        int i;
        String str4;
        String str5;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        Long l;
        String str23;
        String str24;
        Long l2;
        List list3;
        String str25;
        Map map;
        String str26;
        String str27;
        String str28;
        String str29;
        String str30;
        String str31;
        String str32;
        String str33;
        String str34;
        String str35;
        Map map2;
        KSerializer[] kSerializerArr2;
        List list4;
        String str36;
        String str37;
        String str38;
        String str39;
        String str40;
        String str41;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder beginStructure = decoder.beginStructure(descriptor2);
        kSerializerArr = AppV1.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            List list5 = (List) beginStructure.decodeSerializableElement(descriptor2, 0, kSerializerArr[0], null);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str42 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 3, stringSerializer, null);
            String str43 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 11, stringSerializer, null);
            String str44 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 12, stringSerializer, null);
            String str45 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 13, stringSerializer, null);
            String str46 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 14, stringSerializer, null);
            String str47 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 15, stringSerializer, null);
            String str48 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 16, stringSerializer, null);
            String str49 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 17, stringSerializer, null);
            String str50 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 18, stringSerializer, null);
            String str51 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 19, stringSerializer, null);
            String str52 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 20, stringSerializer, null);
            String str53 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 21, stringSerializer, null);
            String str54 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 22, stringSerializer, null);
            String decodeStringElement = beginStructure.decodeStringElement(descriptor2, 23);
            String str55 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 24, stringSerializer, null);
            LongSerializer longSerializer = LongSerializer.INSTANCE;
            Long l3 = (Long) beginStructure.decodeNullableSerializableElement(descriptor2, 25, longSerializer, null);
            String decodeStringElement2 = beginStructure.decodeStringElement(descriptor2, 27);
            Long l4 = (Long) beginStructure.decodeNullableSerializableElement(descriptor2, 28, longSerializer, null);
            str10 = str50;
            list3 = (List) beginStructure.decodeNullableSerializableElement(descriptor2, 30, kSerializerArr[30], null);
            map = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 29, kSerializerArr[29], null);
            i = Integer.MAX_VALUE;
            str7 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 8, stringSerializer, null);
            str16 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 4, stringSerializer, null);
            str25 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 2, stringSerializer, null);
            str24 = decodeStringElement2;
            str21 = decodeStringElement;
            str6 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 10, stringSerializer, null);
            str = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 9, stringSerializer, null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 7, stringSerializer, null);
            str9 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 6, stringSerializer, null);
            str2 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 5, stringSerializer, null);
            str11 = str49;
            str12 = str48;
            str13 = str47;
            str14 = str46;
            str15 = str45;
            l2 = l4;
            str4 = str44;
            str5 = str43;
            list = list5;
            str17 = str51;
            str18 = str52;
            str19 = str53;
            str22 = str55;
            str20 = str54;
            list2 = (List) beginStructure.decodeSerializableElement(descriptor2, 1, kSerializerArr[1], null);
            str3 = str42;
            l = l3;
            str23 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 26, stringSerializer, null);
        } else {
            String str56 = null;
            String str57 = null;
            String str58 = null;
            String str59 = null;
            String str60 = null;
            String str61 = null;
            String str62 = null;
            String str63 = null;
            String str64 = null;
            List list6 = null;
            String str65 = null;
            String str66 = null;
            String str67 = null;
            String str68 = null;
            String str69 = null;
            String str70 = null;
            String str71 = null;
            String str72 = null;
            String str73 = null;
            String str74 = null;
            String str75 = null;
            String str76 = null;
            String str77 = null;
            Long l5 = null;
            String str78 = null;
            String str79 = null;
            Long l6 = null;
            Map map3 = null;
            List list7 = null;
            boolean z = true;
            String str80 = null;
            int i2 = 0;
            List list8 = null;
            while (z) {
                int decodeElementIndex = beginStructure.decodeElementIndex(descriptor2);
                switch (decodeElementIndex) {
                    case -1:
                        str26 = str56;
                        str27 = str80;
                        str28 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str35 = str72;
                        map2 = map3;
                        kSerializerArr2 = kSerializerArr;
                        Unit unit = Unit.INSTANCE;
                        list4 = list8;
                        z = false;
                        str36 = str28;
                        str56 = str26;
                        str37 = str35;
                        str80 = str27;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3;
                    case 0:
                        str26 = str56;
                        str27 = str80;
                        str28 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str35 = str72;
                        map2 = map3;
                        kSerializerArr2 = kSerializerArr;
                        i2 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        list6 = (List) beginStructure.decodeSerializableElement(descriptor2, 0, kSerializerArr[0], list6);
                        list4 = list8;
                        str36 = str28;
                        str56 = str26;
                        str37 = str35;
                        str80 = str27;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32;
                    case 1:
                        List list9 = list8;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str39 = str80;
                        i2 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        list4 = (List) beginStructure.decodeSerializableElement(descriptor2, 1, kSerializerArr[1], list9);
                        str36 = str65;
                        str56 = str56;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322;
                    case 2:
                        list4 = list8;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        String str81 = str71;
                        String str82 = str72;
                        map2 = map3;
                        String str83 = str56;
                        i2 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str56 = str83;
                        str37 = str82;
                        str71 = str81;
                        str80 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 2, StringSerializer.INSTANCE, str80);
                        str36 = str65;
                        continue;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222;
                    case 3:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str59 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 3, StringSerializer.INSTANCE, str59);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222;
                    case 4:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str56 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 4, StringSerializer.INSTANCE, str56);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222;
                    case 5:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str58 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 5, StringSerializer.INSTANCE, str58);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222222;
                    case 6:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str64 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 6, StringSerializer.INSTANCE, str64);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222222;
                    case 7:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str63 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 7, StringSerializer.INSTANCE, str63);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222222;
                    case 8:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str62 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 8, StringSerializer.INSTANCE, str62);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222222222;
                    case 9:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str57 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 9, StringSerializer.INSTANCE, str57);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222222222;
                    case 10:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str61 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 10, StringSerializer.INSTANCE, str61);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222222222;
                    case 11:
                        list4 = list8;
                        str39 = str80;
                        str40 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        i2 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str60 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 11, StringSerializer.INSTANCE, str60);
                        str36 = str40;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222222222222;
                    case 12:
                        list4 = list8;
                        str39 = str80;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str29 = str66;
                        str36 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 12, StringSerializer.INSTANCE, str65);
                        i2 |= PKIFailureInfo.certConfirmed;
                        Unit unit14 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222222222222;
                    case 13:
                        list4 = list8;
                        str39 = str80;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str30 = str67;
                        i2 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str29 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 13, StringSerializer.INSTANCE, str66);
                        str36 = str65;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222222222222;
                    case 14:
                        list4 = list8;
                        str39 = str80;
                        str32 = str69;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str31 = str68;
                        i2 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str30 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 14, StringSerializer.INSTANCE, str67);
                        str36 = str65;
                        str29 = str66;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222222222222222;
                    case 15:
                        list4 = list8;
                        str39 = str80;
                        str33 = str70;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str32 = str69;
                        i2 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str31 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 15, StringSerializer.INSTANCE, str68);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222222222222222;
                    case 16:
                        list4 = list8;
                        str39 = str80;
                        str34 = str71;
                        str38 = str72;
                        map2 = map3;
                        str33 = str70;
                        i2 |= PKIFailureInfo.notAuthorized;
                        Unit unit18 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str32 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 16, StringSerializer.INSTANCE, str69);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222222222222222;
                    case 17:
                        list4 = list8;
                        str39 = str80;
                        String str84 = str71;
                        str38 = str72;
                        map2 = map3;
                        str34 = str84;
                        i2 |= PKIFailureInfo.unsupportedVersion;
                        Unit unit19 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str33 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 17, StringSerializer.INSTANCE, str70);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str37 = str38;
                        str80 = str39;
                        str71 = str34;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr3222222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr3222222222222222222;
                    case 18:
                        list4 = list8;
                        String str85 = str80;
                        String str86 = str72;
                        map2 = map3;
                        i2 |= PKIFailureInfo.transactionIdInUse;
                        Unit unit20 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str37 = str86;
                        str80 = str85;
                        str71 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 18, StringSerializer.INSTANCE, str71);
                        str36 = str65;
                        continue;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr32222222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr32222222222222222222;
                    case 19:
                        list4 = list8;
                        map2 = map3;
                        i2 |= PKIFailureInfo.signerNotTrusted;
                        Unit unit21 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        str37 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 19, StringSerializer.INSTANCE, str72);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        str80 = str80;
                        continue;
                        str65 = str36;
                        str70 = str33;
                        str69 = str32;
                        str68 = str31;
                        str67 = str30;
                        str66 = str29;
                        list8 = list4;
                        map3 = map2;
                        KSerializer[] kSerializerArr322222222222222222222 = kSerializerArr2;
                        str72 = str37;
                        kSerializerArr = kSerializerArr322222222222222222222;
                    case 20:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= PKIFailureInfo.badCertTemplate;
                        Unit unit22 = Unit.INSTANCE;
                        str73 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 20, StringSerializer.INSTANCE, str73);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 21:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= PKIFailureInfo.badSenderNonce;
                        Unit unit23 = Unit.INSTANCE;
                        str74 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 21, StringSerializer.INSTANCE, str74);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 22:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        str75 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 22, StringSerializer.INSTANCE, str75);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 23:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        String decodeStringElement3 = beginStructure.decodeStringElement(descriptor2, 23);
                        i2 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        str76 = decodeStringElement3;
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 24:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        str77 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 24, StringSerializer.INSTANCE, str77);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 25:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= 33554432;
                        Unit unit27 = Unit.INSTANCE;
                        l5 = (Long) beginStructure.decodeNullableSerializableElement(descriptor2, 25, LongSerializer.INSTANCE, l5);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 26:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= 67108864;
                        Unit unit28 = Unit.INSTANCE;
                        str78 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 26, StringSerializer.INSTANCE, str78);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 27:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        String decodeStringElement4 = beginStructure.decodeStringElement(descriptor2, 27);
                        i2 |= 134217728;
                        Unit unit29 = Unit.INSTANCE;
                        str79 = decodeStringElement4;
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 28:
                        list4 = list8;
                        str41 = str80;
                        map2 = map3;
                        i2 |= 268435456;
                        Unit unit30 = Unit.INSTANCE;
                        l6 = (Long) beginStructure.decodeNullableSerializableElement(descriptor2, 28, LongSerializer.INSTANCE, l6);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 29:
                        list4 = list8;
                        str41 = str80;
                        i2 |= PKIFailureInfo.duplicateCertReq;
                        Unit unit31 = Unit.INSTANCE;
                        map2 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 29, kSerializerArr[29], map3);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        break;
                    case 30:
                        list4 = list8;
                        str41 = str80;
                        i2 |= 1073741824;
                        Unit unit32 = Unit.INSTANCE;
                        list7 = (List) beginStructure.decodeNullableSerializableElement(descriptor2, 30, kSerializerArr[30], list7);
                        str36 = str65;
                        str29 = str66;
                        str30 = str67;
                        str31 = str68;
                        str32 = str69;
                        str33 = str70;
                        map2 = map3;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str80 = str41;
                String str87 = str72;
                kSerializerArr2 = kSerializerArr;
                str37 = str87;
                str65 = str36;
                str70 = str33;
                str69 = str32;
                str68 = str31;
                str67 = str30;
                str66 = str29;
                list8 = list4;
                map3 = map2;
                KSerializer[] kSerializerArr3222222222222222222222 = kSerializerArr2;
                str72 = str37;
                kSerializerArr = kSerializerArr3222222222222222222222;
            }
            list = list6;
            list2 = list8;
            str = str57;
            str2 = str58;
            str3 = str59;
            i = i2;
            str4 = str65;
            str5 = str60;
            str6 = str61;
            str7 = str62;
            str8 = str63;
            str9 = str64;
            str10 = str71;
            str11 = str70;
            str12 = str69;
            str13 = str68;
            str14 = str67;
            str15 = str66;
            str16 = str56;
            str17 = str72;
            str18 = str73;
            str19 = str74;
            str20 = str75;
            str21 = str76;
            str22 = str77;
            l = l5;
            str23 = str78;
            str24 = str79;
            l2 = l6;
            list3 = list7;
            str25 = str80;
            map = map3;
        }
        beginStructure.endStructure(descriptor2);
        return new AppV1(i, list, list2, str25, str3, str16, str2, str9, str8, str7, str, str6, str5, str4, str15, str14, str13, str12, str11, str10, str17, str18, str19, str20, str21, str22, l, str23, str24, l2, map, list3, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(Encoder encoder, AppV1 value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder beginStructure = encoder.beginStructure(descriptor2);
        AppV1.write$Self$index_release(value, beginStructure, descriptor2);
        beginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
