package org.fdroid.index.v2;

import ch.qos.logback.core.joran.action.Action;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.bouncycastle.asn1.cmp.PKIFailureInfo;
import org.bouncycastle.i18n.ErrorBundle;
import org.fdroid.fdroid.views.apps.AppListActivity;
/* compiled from: PackageV2.kt */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"org/fdroid/index/v2/MetadataV2.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lorg/fdroid/index/v2/MetadataV2;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", Action.VALUE_ATTRIBUTE, "index_release"}, k = 1, mv = {1, 9, 0}, xi = 48)
/* loaded from: classes2.dex */
public final class MetadataV2$$serializer implements GeneratedSerializer {
    public static final MetadataV2$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    private MetadataV2$$serializer() {
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        MetadataV2$$serializer metadataV2$$serializer = new MetadataV2$$serializer();
        INSTANCE = metadataV2$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("org.fdroid.index.v2.MetadataV2", metadataV2$$serializer, 30);
        pluginGeneratedSerialDescriptor.addElement("name", true);
        pluginGeneratedSerialDescriptor.addElement(ErrorBundle.SUMMARY_ENTRY, true);
        pluginGeneratedSerialDescriptor.addElement("description", true);
        pluginGeneratedSerialDescriptor.addElement("added", false);
        pluginGeneratedSerialDescriptor.addElement(AppListActivity.SortClause.LAST_UPDATED, false);
        pluginGeneratedSerialDescriptor.addElement("webSite", true);
        pluginGeneratedSerialDescriptor.addElement("changelog", true);
        pluginGeneratedSerialDescriptor.addElement("license", true);
        pluginGeneratedSerialDescriptor.addElement("sourceCode", true);
        pluginGeneratedSerialDescriptor.addElement("issueTracker", true);
        pluginGeneratedSerialDescriptor.addElement("translation", true);
        pluginGeneratedSerialDescriptor.addElement("preferredSigner", true);
        pluginGeneratedSerialDescriptor.addElement("categories", true);
        pluginGeneratedSerialDescriptor.addElement("authorName", true);
        pluginGeneratedSerialDescriptor.addElement("authorEmail", true);
        pluginGeneratedSerialDescriptor.addElement("authorWebSite", true);
        pluginGeneratedSerialDescriptor.addElement("authorPhone", true);
        pluginGeneratedSerialDescriptor.addElement("donate", true);
        pluginGeneratedSerialDescriptor.addElement("liberapayID", true);
        pluginGeneratedSerialDescriptor.addElement("liberapay", true);
        pluginGeneratedSerialDescriptor.addElement("openCollective", true);
        pluginGeneratedSerialDescriptor.addElement("bitcoin", true);
        pluginGeneratedSerialDescriptor.addElement("litecoin", true);
        pluginGeneratedSerialDescriptor.addElement("flattrID", true);
        pluginGeneratedSerialDescriptor.addElement("icon", true);
        pluginGeneratedSerialDescriptor.addElement("featureGraphic", true);
        pluginGeneratedSerialDescriptor.addElement("promoGraphic", true);
        pluginGeneratedSerialDescriptor.addElement("tvBanner", true);
        pluginGeneratedSerialDescriptor.addElement("video", true);
        pluginGeneratedSerialDescriptor.addElement("screenshots", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] childSerializers() {
        KSerializer[] kSerializerArr;
        kSerializerArr = MetadataV2.$childSerializers;
        LongSerializer longSerializer = LongSerializer.INSTANCE;
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        return new KSerializer[]{BuiltinSerializersKt.getNullable(kSerializerArr[0]), BuiltinSerializersKt.getNullable(kSerializerArr[1]), BuiltinSerializersKt.getNullable(kSerializerArr[2]), longSerializer, longSerializer, BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), kSerializerArr[12], BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), kSerializerArr[17], BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(kSerializerArr[24]), BuiltinSerializersKt.getNullable(kSerializerArr[25]), BuiltinSerializersKt.getNullable(kSerializerArr[26]), BuiltinSerializersKt.getNullable(kSerializerArr[27]), BuiltinSerializersKt.getNullable(kSerializerArr[28]), BuiltinSerializersKt.getNullable(Screenshots$$serializer.INSTANCE)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    public MetadataV2 deserialize(Decoder decoder) {
        KSerializer[] kSerializerArr;
        Map map;
        Map map2;
        Map map3;
        Map map4;
        String str;
        String str2;
        String str3;
        Map map5;
        String str4;
        Map map6;
        Screenshots screenshots;
        List list;
        String str5;
        List list2;
        String str6;
        String str7;
        String str8;
        String str9;
        String str10;
        String str11;
        Map map7;
        String str12;
        String str13;
        String str14;
        String str15;
        long j;
        long j2;
        String str16;
        String str17;
        Map map8;
        int i;
        Map map9;
        String str18;
        String str19;
        String str20;
        String str21;
        String str22;
        String str23;
        String str24;
        List list3;
        List list4;
        KSerializer[] kSerializerArr2;
        String str25;
        Map map10;
        Map map11;
        String str26;
        Map map12;
        String str27;
        int i2;
        int i3;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder beginStructure = decoder.beginStructure(descriptor2);
        kSerializerArr = MetadataV2.$childSerializers;
        if (beginStructure.decodeSequentially()) {
            Map map13 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 0, kSerializerArr[0], null);
            long decodeLongElement = beginStructure.decodeLongElement(descriptor2, 3);
            long decodeLongElement2 = beginStructure.decodeLongElement(descriptor2, 4);
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            String str28 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 10, stringSerializer, null);
            List list5 = (List) beginStructure.decodeSerializableElement(descriptor2, 12, kSerializerArr[12], null);
            String str29 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 14, stringSerializer, null);
            String str30 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 15, stringSerializer, null);
            String str31 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 16, stringSerializer, null);
            List list6 = (List) beginStructure.decodeSerializableElement(descriptor2, 17, kSerializerArr[17], null);
            String str32 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 19, stringSerializer, null);
            String str33 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 20, stringSerializer, null);
            String str34 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 21, stringSerializer, null);
            String str35 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 22, stringSerializer, null);
            String str36 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 23, stringSerializer, null);
            Map map14 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 24, kSerializerArr[24], null);
            Map map15 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 25, kSerializerArr[25], null);
            Map map16 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 26, kSerializerArr[26], null);
            map5 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 28, kSerializerArr[28], null);
            screenshots = (Screenshots) beginStructure.decodeNullableSerializableElement(descriptor2, 29, Screenshots$$serializer.INSTANCE, null);
            map6 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 27, kSerializerArr[27], null);
            i = 1073741823;
            str16 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 18, stringSerializer, null);
            str9 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 9, stringSerializer, null);
            str7 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 7, stringSerializer, null);
            str6 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 6, stringSerializer, null);
            str12 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 5, stringSerializer, null);
            map2 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 1, kSerializerArr[1], null);
            str8 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 8, stringSerializer, null);
            str11 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 11, stringSerializer, null);
            map7 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 2, kSerializerArr[2], null);
            str5 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 13, stringSerializer, null);
            map8 = map16;
            map3 = map15;
            map4 = map14;
            str4 = str36;
            str10 = str28;
            str15 = str31;
            map = map13;
            list2 = list5;
            j = decodeLongElement;
            j2 = decodeLongElement2;
            str13 = str29;
            str14 = str30;
            list = list6;
            str17 = str32;
            str3 = str33;
            str2 = str34;
            str = str35;
        } else {
            Map map17 = null;
            Map map18 = null;
            Map map19 = null;
            String str37 = null;
            String str38 = null;
            String str39 = null;
            String str40 = null;
            String str41 = null;
            String str42 = null;
            Screenshots screenshots2 = null;
            Map map20 = null;
            Map map21 = null;
            Map map22 = null;
            String str43 = null;
            String str44 = null;
            String str45 = null;
            String str46 = null;
            String str47 = null;
            String str48 = null;
            String str49 = null;
            List list7 = null;
            String str50 = null;
            String str51 = null;
            String str52 = null;
            String str53 = null;
            List list8 = null;
            boolean z = true;
            long j3 = 0;
            long j4 = 0;
            Map map23 = null;
            int i4 = 0;
            Map map24 = null;
            while (z) {
                String str54 = str40;
                int decodeElementIndex = beginStructure.decodeElementIndex(descriptor2);
                switch (decodeElementIndex) {
                    case -1:
                        map9 = map17;
                        str18 = str42;
                        Map map25 = map21;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        kSerializerArr2 = kSerializerArr;
                        str25 = str53;
                        Unit unit = Unit.INSTANCE;
                        map10 = map25;
                        z = false;
                        break;
                    case 0:
                        map9 = map17;
                        str18 = str42;
                        Map map26 = map21;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        kSerializerArr2 = kSerializerArr;
                        i4 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        map20 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 0, kSerializerArr[0], map20);
                        map10 = map26;
                        break;
                    case 1:
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        i4 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        kSerializerArr2 = kSerializerArr;
                        map10 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 1, kSerializerArr[1], map21);
                        str42 = str42;
                        map17 = map17;
                        continue;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3;
                    case 2:
                        map11 = map17;
                        str26 = str42;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        i4 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        map22 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 2, kSerializerArr[2], map22);
                        str42 = str26;
                        map17 = map11;
                        Map map27 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32;
                    case 3:
                        map11 = map17;
                        str26 = str42;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        j3 = beginStructure.decodeLongElement(descriptor2, 3);
                        i4 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        str42 = str26;
                        map17 = map11;
                        Map map272 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322;
                    case 4:
                        map11 = map17;
                        str26 = str42;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        j4 = beginStructure.decodeLongElement(descriptor2, 4);
                        i4 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        str42 = str26;
                        map17 = map11;
                        Map map2722 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222;
                    case 5:
                        map11 = map17;
                        str26 = str42;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str19 = str44;
                        i4 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        str43 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 5, StringSerializer.INSTANCE, str43);
                        str42 = str26;
                        map17 = map11;
                        Map map27222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222;
                    case 6:
                        map11 = map17;
                        str26 = str42;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str20 = str45;
                        i4 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        str19 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 6, StringSerializer.INSTANCE, str44);
                        str42 = str26;
                        map17 = map11;
                        Map map272222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222;
                    case 7:
                        map11 = map17;
                        str26 = str42;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str21 = str46;
                        i4 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        str20 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 7, StringSerializer.INSTANCE, str45);
                        str19 = str44;
                        str42 = str26;
                        map17 = map11;
                        Map map2722222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222;
                    case 8:
                        map11 = map17;
                        str26 = str42;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str22 = str47;
                        i4 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        str21 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 8, StringSerializer.INSTANCE, str46);
                        str19 = str44;
                        str20 = str45;
                        str42 = str26;
                        map17 = map11;
                        Map map27222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222;
                    case 9:
                        map11 = map17;
                        str26 = str42;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str23 = str48;
                        i4 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        str22 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 9, StringSerializer.INSTANCE, str47);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str42 = str26;
                        map17 = map11;
                        Map map272222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222;
                    case 10:
                        map11 = map17;
                        str26 = str42;
                        list3 = list7;
                        list4 = list8;
                        str25 = str53;
                        str24 = str49;
                        i4 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        str23 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 10, StringSerializer.INSTANCE, str48);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str42 = str26;
                        map17 = map11;
                        Map map2722222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222;
                    case 11:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        str25 = str53;
                        list3 = list7;
                        i4 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        str24 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 11, StringSerializer.INSTANCE, str49);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str42 = str26;
                        map17 = map11;
                        Map map27222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222;
                    case 12:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        str25 = str53;
                        i4 |= PKIFailureInfo.certConfirmed;
                        Unit unit14 = Unit.INSTANCE;
                        list3 = (List) beginStructure.decodeSerializableElement(descriptor2, 12, kSerializerArr[12], list7);
                        str50 = str50;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        str42 = str26;
                        map17 = map11;
                        Map map272222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222;
                    case 13:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        str25 = str53;
                        i4 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        str50 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 13, StringSerializer.INSTANCE, str50);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        str42 = str26;
                        map17 = map11;
                        Map map2722222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222;
                    case 14:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        str25 = str53;
                        i4 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        str51 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 14, StringSerializer.INSTANCE, str51);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        str42 = str26;
                        map17 = map11;
                        Map map27222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222;
                    case 15:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        str25 = str53;
                        i4 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        str52 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 15, StringSerializer.INSTANCE, str52);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        str42 = str26;
                        map17 = map11;
                        Map map272222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222222;
                    case 16:
                        map11 = map17;
                        str26 = str42;
                        list4 = list8;
                        i4 |= PKIFailureInfo.notAuthorized;
                        Unit unit18 = Unit.INSTANCE;
                        str25 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 16, StringSerializer.INSTANCE, str53);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        str42 = str26;
                        map17 = map11;
                        Map map2722222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222222;
                    case 17:
                        map11 = map17;
                        str26 = str42;
                        i4 |= PKIFailureInfo.unsupportedVersion;
                        Unit unit19 = Unit.INSTANCE;
                        list4 = (List) beginStructure.decodeSerializableElement(descriptor2, 17, kSerializerArr[17], list8);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        str25 = str53;
                        str42 = str26;
                        map17 = map11;
                        Map map27222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222222;
                    case 18:
                        map12 = map17;
                        i4 |= PKIFailureInfo.transactionIdInUse;
                        Unit unit20 = Unit.INSTANCE;
                        str54 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 18, StringSerializer.INSTANCE, str54);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str42;
                        map17 = map12;
                        str25 = str53;
                        Map map272222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222222222;
                    case 19:
                        map12 = map17;
                        i4 |= PKIFailureInfo.signerNotTrusted;
                        Unit unit21 = Unit.INSTANCE;
                        str42 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 19, StringSerializer.INSTANCE, str42);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        map17 = map12;
                        str25 = str53;
                        Map map2722222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222222222;
                    case 20:
                        str27 = str42;
                        str39 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 20, StringSerializer.INSTANCE, str39);
                        i2 = PKIFailureInfo.badCertTemplate;
                        i4 |= i2;
                        Unit unit22 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map27222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222222222;
                    case 21:
                        str27 = str42;
                        str38 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 21, StringSerializer.INSTANCE, str38);
                        i2 = PKIFailureInfo.badSenderNonce;
                        i4 |= i2;
                        Unit unit222 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map272222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222222222222;
                    case 22:
                        str27 = str42;
                        str37 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 22, StringSerializer.INSTANCE, str37);
                        i2 = 4194304;
                        i4 |= i2;
                        Unit unit2222 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map2722222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222222222222;
                    case 23:
                        str27 = str42;
                        i4 |= 8388608;
                        Unit unit23 = Unit.INSTANCE;
                        str41 = (String) beginStructure.decodeNullableSerializableElement(descriptor2, 23, StringSerializer.INSTANCE, str41);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map27222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222222222222;
                    case 24:
                        str27 = str42;
                        map19 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 24, kSerializerArr[24], map19);
                        i3 = 16777216;
                        i4 |= i3;
                        Unit unit24 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map272222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222222222222222;
                    case 25:
                        str27 = str42;
                        map18 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 25, kSerializerArr[25], map18);
                        i2 = 33554432;
                        i4 |= i2;
                        Unit unit22222 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map2722222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222222222222222;
                    case 26:
                        str27 = str42;
                        map17 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 26, kSerializerArr[26], map17);
                        i3 = 67108864;
                        i4 |= i3;
                        Unit unit242 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map27222222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222222222222222;
                    case 27:
                        str27 = str42;
                        i4 |= 134217728;
                        Unit unit25 = Unit.INSTANCE;
                        map24 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 27, kSerializerArr[27], map24);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map272222222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map272222222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr322222222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr322222222222222222222222222;
                    case 28:
                        str27 = str42;
                        map23 = (Map) beginStructure.decodeNullableSerializableElement(descriptor2, 28, kSerializerArr[28], map23);
                        i3 = 268435456;
                        i4 |= i3;
                        Unit unit2422 = Unit.INSTANCE;
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map2722222222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map2722222222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr3222222222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr3222222222222222222222222222;
                    case 29:
                        str27 = str42;
                        i4 |= PKIFailureInfo.duplicateCertReq;
                        Unit unit26 = Unit.INSTANCE;
                        screenshots2 = (Screenshots) beginStructure.decodeNullableSerializableElement(descriptor2, 29, Screenshots$$serializer.INSTANCE, screenshots2);
                        str19 = str44;
                        str20 = str45;
                        str21 = str46;
                        str22 = str47;
                        str23 = str48;
                        str24 = str49;
                        list3 = list7;
                        list4 = list8;
                        str42 = str27;
                        str25 = str53;
                        Map map27222222222222222222222222222 = map21;
                        kSerializerArr2 = kSerializerArr;
                        map10 = map27222222222222222222222222222;
                        list7 = list3;
                        str44 = str19;
                        str45 = str20;
                        str46 = str21;
                        str47 = str22;
                        str48 = str23;
                        str49 = str24;
                        str53 = str25;
                        str40 = str54;
                        list8 = list4;
                        KSerializer[] kSerializerArr32222222222222222222222222222 = kSerializerArr2;
                        map21 = map10;
                        kSerializerArr = kSerializerArr32222222222222222222222222222;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                str42 = str18;
                map17 = map9;
                list7 = list3;
                str44 = str19;
                str45 = str20;
                str46 = str21;
                str47 = str22;
                str48 = str23;
                str49 = str24;
                str53 = str25;
                str40 = str54;
                list8 = list4;
                KSerializer[] kSerializerArr322222222222222222222222222222 = kSerializerArr2;
                map21 = map10;
                kSerializerArr = kSerializerArr322222222222222222222222222222;
            }
            map = map20;
            map2 = map21;
            map3 = map18;
            map4 = map19;
            str = str37;
            str2 = str38;
            str3 = str39;
            map5 = map23;
            str4 = str41;
            map6 = map24;
            screenshots = screenshots2;
            list = list8;
            str5 = str50;
            list2 = list7;
            str6 = str44;
            str7 = str45;
            str8 = str46;
            str9 = str47;
            str10 = str48;
            str11 = str49;
            map7 = map22;
            str12 = str43;
            str13 = str51;
            str14 = str52;
            str15 = str53;
            j = j3;
            j2 = j4;
            str16 = str40;
            str17 = str42;
            map8 = map17;
            i = i4;
        }
        beginStructure.endStructure(descriptor2);
        return new MetadataV2(i, map, map2, map7, j, j2, str12, str6, str7, str8, str9, str10, str11, list2, str5, str13, str14, str15, list, str16, str17, str3, str2, str, str4, map4, map3, map8, map6, map5, screenshots, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(Encoder encoder, MetadataV2 value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder beginStructure = encoder.beginStructure(descriptor2);
        MetadataV2.write$Self$index_release(value, beginStructure, descriptor2);
        beginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    public KSerializer[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
